"""fix_enums_and_add_compoff_v2

Revision ID: 024d2104e652
Revises: 9a21236568d3
Create Date: 2025-12-23 04:00:17.067831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024d2104e652'
down_revision = '9a21236568d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Update data casing to uppercase (to match Enum values)
    op.execute("UPDATE leaves SET status = UPPER(status)")
    op.execute("UPDATE leaves SET leave_type = UPPER(leave_type)")
    op.execute("UPDATE notifications SET status = UPPER(status)")
    op.execute("UPDATE notifications SET notification_type = UPPER(notification_type)")
    
    # 2. Ensure types exist (Idempotent)
    # Replaced DROP TYPE CASCADE with safe creation
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'leavetype') THEN CREATE TYPE leavetype AS ENUM ('ANNUAL', 'SICK', 'CASUAL', 'UNPAID', 'MATERNITY', 'PATERNITY', 'BEREAVEMENT', 'OTHER'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'leavestatus') THEN CREATE TYPE leavestatus AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notificationtype') THEN CREATE TYPE notificationtype AS ENUM ('FORGOT_CHECKIN', 'FORGOT_CHECKOUT', 'LEAVE_APPROVED', 'LEAVE_REJECTED', 'LATE_ARRIVAL', 'AUTO_CHECKOUT', 'GENERAL'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notificationstatus') THEN CREATE TYPE notificationstatus AS ENUM ('UNREAD', 'READ'); END IF; END $$;")
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'compoffstatus') THEN CREATE TYPE compoffstatus AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'USED'); END IF; END $$;")

    # 3. Create tables and columns (types will be created automatically by SA)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'comp_offs' not in tables:
        op.create_table('comp_offs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('ot_hours', sa.Float(), nullable=False),
        sa.Column('comp_off_days', sa.Float(), nullable=False),
        sa.Column('ot_start_date', sa.DateTime(), nullable=False),
        sa.Column('ot_end_date', sa.DateTime(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'USED', name='compoffstatus'), nullable=False),
        sa.Column('request_date', sa.DateTime(), nullable=False),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
        sa.Column('review_date', sa.DateTime(), nullable=True),
        sa.Column('admin_remarks', sa.String(), nullable=True),
        sa.Column('leave_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['leave_id'], ['leaves.id'], ),
        sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_comp_offs_id'), 'comp_offs', ['id'], unique=False)
        op.create_index(op.f('ix_comp_offs_user_id'), 'comp_offs', ['user_id'], unique=False)
    
    # Check checks for checkinouts columns to be safe, though not strictly required if only table creation failed
    checkinout_columns = [c['name'] for c in inspector.get_columns('checkinouts')]
    if 'is_late_arrival' not in checkinout_columns:
        op.add_column('checkinouts', sa.Column('is_late_arrival', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    if 'late_minutes' not in checkinout_columns:
        op.add_column('checkinouts', sa.Column('late_minutes', sa.Integer(), nullable=False, server_default=sa.text('0')))
    if 'is_early_exit' not in checkinout_columns:
        op.add_column('checkinouts', sa.Column('is_early_exit', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    if 'early_exit_minutes' not in checkinout_columns:
        op.add_column('checkinouts', sa.Column('early_exit_minutes', sa.Integer(), nullable=False, server_default=sa.text('0')))

    # Remove server defaults if we don't want them permanently (optional, but good practice if nullable=False was the goal without default)
    # The original script had nullable=False for these add_columns which implies they need a default on creation if table has data.
    # The original script logic for add_column was:
    # op.add_column('checkinouts', sa.Column('is_late_arrival', sa.Boolean(), nullable=False))
    # This would FAIL if data exists anyway. I should probably add server_default.

    
    # 4. Alter columns with explicit casting using postgresql_using
    op.alter_column('checkinouts', 'shift_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'regular'::character varying"))
    op.alter_column('checkinouts', 'shift_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('checkinouts', 'is_location_valid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('checkinouts', 'is_auto_checkout',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'checkinouts', 'users', ['modified_by_admin_id'], ['id'])
    
    op.execute("ALTER TABLE leaves ALTER COLUMN status DROP DEFAULT")
    op.alter_column('leaves', 'leave_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ANNUAL', 'SICK', 'CASUAL', 'UNPAID', 'MATERNITY', 'PATERNITY', 'BEREAVEMENT', 'OTHER', name='leavetype'),
               existing_nullable=False,
               postgresql_using="leave_type::text::leavetype")
    op.alter_column('leaves', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"),
               server_default=sa.text("'PENDING'::leavestatus"),
               postgresql_using="status::text::leavestatus")
    
    op.execute("ALTER TABLE notifications ALTER COLUMN status DROP DEFAULT")
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('FORGOT_CHECKIN', 'FORGOT_CHECKOUT', 'LEAVE_APPROVED', 'LEAVE_REJECTED', 'LATE_ARRIVAL', 'AUTO_CHECKOUT', 'GENERAL', name='notificationtype'),
               existing_nullable=False,
               postgresql_using="notification_type::text::notificationtype")
    op.alter_column('notifications', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('UNREAD', 'READ', name='notificationstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'unread'::character varying"),
               server_default=sa.text("'UNREAD'::notificationstatus"),
               postgresql_using="status::text::notificationstatus")
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    op.alter_column('notifications', 'status',
               existing_type=sa.Enum('UNREAD', 'READ', name='notificationstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'unread'::character varying"))
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.Enum('FORGOT_CHECKIN', 'FORGOT_CHECKOUT', 'LEAVE_APPROVED', 'LEAVE_REJECTED', 'LATE_ARRIVAL', 'AUTO_CHECKOUT', 'GENERAL', name='notificationtype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('leaves', 'status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('leaves', 'leave_type',
               existing_type=sa.Enum('ANNUAL', 'SICK', 'CASUAL', 'UNPAID', 'MATERNITY', 'PATERNITY', 'BEREAVEMENT', 'OTHER', name='leavetype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'checkinouts', type_='foreignkey')
    op.alter_column('checkinouts', 'is_auto_checkout',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('checkinouts', 'is_location_valid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('checkinouts', 'shift_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('checkinouts', 'shift_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'regular'::character varying"))
    op.drop_column('checkinouts', 'early_exit_minutes')
    op.drop_column('checkinouts', 'is_early_exit')
    op.drop_column('checkinouts', 'late_minutes')
    op.drop_column('checkinouts', 'is_late_arrival')
    op.drop_index(op.f('ix_comp_offs_user_id'), table_name='comp_offs')
    op.drop_index(op.f('ix_comp_offs_id'), table_name='comp_offs')
    op.drop_table('comp_offs')
    # ### end Alembic commands ###
