"""add_performance_indexes

Revision ID: 5b9a83a303d2
Revises: add_onboarding_notes_fixed
Create Date: 2026-04-01 02:05:44.877627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9a83a303d2'
down_revision = 'add_onboarding_notes_fixed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_checkinouts_user_checkin', 'checkinouts', ['user_id', 'check_in_time'], unique=False)
    op.create_index('ix_leaves_user_status', 'leaves', ['user_id', 'status'], unique=False)
    op.create_index('ix_salary_user_period', 'salary_records', ['user_id', 'year', 'month'], unique=False)
    op.create_unique_constraint('uq_salary_user_period', 'salary_records', ['user_id', 'year', 'month'])
    op.create_index(op.f('ix_users_reset_token'), 'users', ['reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reset_token'), table_name='users')
    op.drop_constraint('uq_salary_user_period', 'salary_records', type_='unique')
    op.drop_index('ix_salary_user_period', table_name='salary_records')
    op.drop_index('ix_leaves_user_status', table_name='leaves')
    op.drop_index('ix_checkinouts_user_checkin', table_name='checkinouts')
    # ### end Alembic commands ###

