"""add onboarding tables

Revision ID: 8ae4723bf709
Revises: 93b6e859efd5
Create Date: 2025-12-29 17:57:21.270528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae4723bf709'
down_revision = '93b6e859efd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_workflows',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_workflows_id'), 'onboarding_workflows', ['id'], unique=False)
    
    op.create_table('onboarding_tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=True),
        sa.Column('is_required', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['workflow_id'], ['onboarding_workflows.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_tasks_id'), 'onboarding_tasks', ['id'], unique=False)
    
    op.create_table('employee_onboardings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('workflow_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['workflow_id'], ['onboarding_workflows.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_onboardings_id'), 'employee_onboardings', ['id'], unique=False)
    
    op.create_table('employee_task_progress',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_onboarding_id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('is_completed', sa.Boolean(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['employee_onboarding_id'], ['employee_onboardings.id'], ),
        sa.ForeignKeyConstraint(['task_id'], ['onboarding_tasks.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_task_progress_id'), 'employee_task_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_task_progress_id'), table_name='employee_task_progress')
    op.drop_table('employee_task_progress')
    op.drop_index(op.f('ix_employee_onboardings_id'), table_name='employee_onboardings')
    op.drop_table('employee_onboardings')
    op.drop_index(op.f('ix_onboarding_tasks_id'), table_name='onboarding_tasks')
    op.drop_table('onboarding_tasks')
    op.drop_index(op.f('ix_onboarding_workflows_id'), table_name='onboarding_workflows')
    op.drop_table('onboarding_workflows')
    # ### end Alembic commands ###
