"""add pulse survey and response tables

Revision ID: 93b6e859efd5
Revises: a1b2c3d4e5f6
Create Date: 2025-12-29 17:49:18.061006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add pulse survey and response tables

Revision ID: 93b6e859efd5
Revises: a1b2c3d4e5f6
Create Date: 2025-12-29 17:49:18.061006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b6e859efd5'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulse_surveys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pulse_surveys_id'), 'pulse_surveys', ['id'], unique=False)
    
    op.create_table('pulse_responses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('survey_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('comment', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['survey_id'], ['pulse_surveys.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pulse_responses_id'), 'pulse_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pulse_responses_id'), table_name='pulse_responses')
    op.drop_table('pulse_responses')
    op.drop_index(op.f('ix_pulse_surveys_id'), table_name='pulse_surveys')
    op.drop_table('pulse_surveys')
    # ### end Alembic commands ###
