"""add_hrms_holiday_salary_tables

Revision ID: 9a21236568d3
Revises: 1ab77cf6a330
Create Date: 2025-12-23 02:08:46.838586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a21236568d3'
down_revision = 'fe7d69513d1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_holiday_date'), 'holidays', ['holiday_date'], unique=True)
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('salary_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monthly_base_salary', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('overtime_multiplier', sa.Float(), nullable=False),
    sa.Column('deduction_rate_per_hour', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_configs_id'), 'salary_configs', ['id'], unique=False)
    op.create_index(op.f('ix_salary_configs_user_id'), 'salary_configs', ['user_id'], unique=False)
    op.create_table('salary_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('office_working_days', sa.Integer(), nullable=False),
    sa.Column('days_worked', sa.Integer(), nullable=False),
    sa.Column('days_absent', sa.Integer(), nullable=False),
    sa.Column('total_hours_worked', sa.Float(), nullable=False),
    sa.Column('expected_hours', sa.Float(), nullable=False),
    sa.Column('average_hours_per_day', sa.Float(), nullable=False),
    sa.Column('overtime_days', sa.Integer(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('undertime_hours', sa.Float(), nullable=False),
    sa.Column('base_salary', sa.Float(), nullable=False),
    sa.Column('hourly_rate_used', sa.Float(), nullable=False),
    sa.Column('overtime_pay', sa.Float(), nullable=False),
    sa.Column('deductions', sa.Float(), nullable=False),
    sa.Column('absence_deductions', sa.Float(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'PAID', 'CANCELLED', name='salarystatus'), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_records_id'), 'salary_records', ['id'], unique=False)
    op.create_index(op.f('ix_salary_records_month'), 'salary_records', ['month'], unique=False)
    op.create_index(op.f('ix_salary_records_user_id'), 'salary_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_salary_records_year'), 'salary_records', ['year'], unique=False)
    # Note: Skipping alter_column for checkinouts columns to preserve existing data
    # The model defines nullable=False but we keep DB nullable=True for backwards compatibility
    op.add_column('users', sa.Column('monthly_base_salary', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_base_salary')
    op.drop_index(op.f('ix_salary_records_year'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_user_id'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_month'), table_name='salary_records')
    op.drop_index(op.f('ix_salary_records_id'), table_name='salary_records')
    op.drop_table('salary_records')
    op.drop_index(op.f('ix_salary_configs_user_id'), table_name='salary_configs')
    op.drop_index(op.f('ix_salary_configs_id'), table_name='salary_configs')
    op.drop_table('salary_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_holidays_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_holiday_date'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###

