"""Create users and checkinouts tables

Revision ID: fe7d69513d1e
Revises: 7d79bced2664
Create Date: 2025-12-19 13:22:53.297383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7d69513d1e'
down_revision = '7d79bced2664'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

