"""
Repository Protocol definitions — the contracts that data access layers must satisfy.

Design principles:
- Protocols use structural typing: any class with matching methods satisfies the protocol
- Repositories never commit — services own transaction boundaries
- Each protocol covers one aggregate root (User, CheckInOut, Leave, etc.)
- Methods return domain models (SQLAlchemy ORM objects) — not dicts

Usage in services:
    class AuthService:
        def __init__(self, user_repo: IUserRepository):
            self.user_repo = user_repo
"""
from typing import Protocol, Optional, List, runtime_checkable
from datetime import datetime, date

# Forward references to avoid circular imports — these are the ORM model types.
# At runtime, any object with the right methods will satisfy the protocol.
from app.models.user import User
from app.models.checkinout import CheckInOut
from app.models.leave import Leave, LeaveStatus
from app.models.salary import SalaryConfig, SalaryRecord
from app.models.holiday import Holiday
from app.models.notification import Notification, NotificationPreferences
from app.models.audit import AuditLog


# ── User Repository ────────────────────────────────────────────────

@runtime_checkable
class IUserRepository(Protocol):
    """Contract for User data access."""

    def get_by_id(self, user_id: int) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def get_by_username(self, username: str) -> Optional[User]: ...
    def email_or_username_exists(self, email: str, username: str) -> Optional[User]: ...
    def get_by_reset_token(self, token: str) -> Optional[User]: ...
    def get_by_email_and_otp(self, email: str, otp: str) -> Optional[User]: ...
    def get_active_users(self) -> List[User]: ...
    def get_all(self, skip: int = 0, limit: int = 100) -> List[User]: ...
    def add(self, obj) -> None: ...


# ── Attendance Repository ──────────────────────────────────────────

@runtime_checkable
class IAttendanceRepository(Protocol):
    """Contract for CheckInOut (attendance) data access."""

    def get_by_id(self, record_id: int) -> Optional[CheckInOut]: ...
    def get_today_record(self, user_id: int, today_start: datetime, today_end: datetime) -> Optional[CheckInOut]: ...
    def get_active_shift(self, user_id: int) -> Optional[CheckInOut]: ...
    def get_pending_records(self, cutoff_time: datetime) -> List[CheckInOut]: ...
    def get_user_history(
        self, user_id: int, skip: int, limit: int,
        start_date: Optional[datetime], end_date: Optional[datetime]
    ) -> List[CheckInOut]: ...
    def get_all_records(
        self, skip: int, limit: int,
        user_id: Optional[int], pending_only: bool
    ) -> List[CheckInOut]: ...
    def get_completed_in_range(
        self, user_id: int, start_date: datetime, end_date: datetime
    ) -> List[CheckInOut]: ...
    def get_all_in_range(
        self, user_id: int, start_date: datetime, end_date: datetime
    ) -> List[CheckInOut]: ...
    def add(self, obj) -> None: ...


# ── Leave Repository ──────────────────────────────────────────────

@runtime_checkable
class ILeaveRepository(Protocol):
    """Contract for Leave data access."""

    def get_by_id(self, leave_id: int) -> Optional[Leave]: ...
    def get_overlapping(self, user_id: int, start_date: date, end_date: date) -> Optional[Leave]: ...
    def get_user_leaves(
        self, user_id: int, skip: int, limit: int,
        status_filter: Optional[LeaveStatus]
    ) -> List[Leave]: ...
    def get_all_leaves(
        self, skip: int, limit: int,
        status_filter: Optional[LeaveStatus], user_id: Optional[int]
    ) -> List[Leave]: ...
    def get_all_for_user(self, user_id: int) -> List[Leave]: ...
    def get_approved_in_range(self, user_id: int, start_date: date, end_date: date) -> List[Leave]: ...
    def add(self, obj) -> None: ...


# ── Salary Repository ─────────────────────────────────────────────

@runtime_checkable
class ISalaryRepository(Protocol):
    """Contract for SalaryConfig and SalaryRecord data access."""

    def get_current_config(self, user_id: int) -> Optional[SalaryConfig]: ...
    def get_active_configs(self, user_id: int) -> List[SalaryConfig]: ...
    def get_record(self, user_id: int, year: int, month: int) -> Optional[SalaryRecord]: ...
    def get_record_by_id(self, record_id: int) -> Optional[SalaryRecord]: ...
    def get_monthly_records(self, year: int, month: int) -> List[SalaryRecord]: ...
    def get_active_users(self, user_id: Optional[int] = None) -> List[User]: ...


# ── Holiday Repository ────────────────────────────────────────────

@runtime_checkable
class IHolidayRepository(Protocol):
    """Contract for Holiday data access."""

    def get_by_id(self, holiday_id: int) -> Optional[Holiday]: ...
    def get_by_date(self, holiday_date: date) -> Optional[Holiday]: ...
    def get_all(
        self, year: Optional[int], active_only: bool,
        skip: int, limit: int
    ) -> List[Holiday]: ...
    def get_in_range(self, start_date: date, end_date: date, active_only: bool) -> List[Holiday]: ...
    def count_in_range(self, start_date: date, end_date: date, active_only: bool) -> int: ...
    def add(self, obj) -> None: ...
    def delete(self, obj) -> None: ...


# ── Notification Repository ───────────────────────────────────────

@runtime_checkable
class INotificationRepository(Protocol):
    """Contract for Notification data access."""

    def get_preferences(self, user_id: int) -> Optional[NotificationPreferences]: ...
    def create_preferences(self, user_id: int) -> NotificationPreferences: ...
    def create_notification(self, notification: Notification) -> None: ...
    def get_for_user(
        self, user_id: int, skip: int, limit: int, unread_only: bool
    ) -> List[Notification]: ...
    def get_unread_count(self, user_id: int) -> dict: ...
    def get_by_id(self, notification_id: int, user_id: int) -> Optional[Notification]: ...
    def mark_all_read(self, user_id: int) -> int: ...
    def delete(self, obj) -> None: ...


# ── Audit Repository ──────────────────────────────────────────────

@runtime_checkable
class IAuditRepository(Protocol):
    """Contract for AuditLog data access."""

    def add(self, obj) -> None: ...
    def get_logs(
        self, skip: int, limit: int,
        user_id: Optional[int], action: Optional[str],
        resource_type: Optional[str],
        start_date: Optional[datetime], end_date: Optional[datetime]
    ) -> tuple: ...
    def get_resource_history(self, resource_type: str, resource_id: str, limit: int) -> List[AuditLog]: ...
    def delete_older_than(self, cutoff: datetime) -> int: ...
